version: '3'
services:
  db:
    image: mysql:5.6.39
    networks:
      - voice-web
    container_name: voiceweb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=voiceweb
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=worxin15324
  s3proxy:
    image: andrewgaul/s3proxy
    container_name: s3proxy
    networks:
      - voice-web
    environment:
      - S3PROXY_AUTHORIZATION=none
      - S3PROXY_CORS_ALLOW_ALL=true
    ports:
      - 8080:80
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    links:
      - db
    volumes:
      - .:/code
    environment:
      - DOTENV_CONFIG_PATH=/code/.env-local-docker
    networks:
      - voice-web
    ports:
      - 9000:9000
    command: bash -c "/code/docker/prepare_s3.sh && yarn && yarn start"
networks:
  voice-web:
